# H2 DB
database:
    driverClass: org.h2.Driver
    user: sa
    password:
    logValidationErrors: false
    url: ${DW_DATABASE_URL:-jdbc:h2:./wanthavers-db}

    properties:
      hibernate.dialect: de.fau.cs.mad.wanthavers.server.misc.FixedH2Dialect
      hibernate.hbm2ddl.auto: ${DW_HBM2DDL:-validate}

server:
  applicationConnectors:
    - keyStorePassword: ${KEYSTOREPW}
      keyStorePath: keystore.jks
      type: https
      port: 8443
      validateCerts: false
#      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts

logging:
  level: WARN

  loggers:
    "de.fau.cs.mad.swipe": DEBUG
# json parsing exceptions
    "io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper": DEBUG

#    hibernate tracing
#    log sql
#    "org.hibernate.SQL": DEBUG
#    parameters of prepared statements
#    "org.hibernate.type": TRACE

#   log incoming/outgoing plain requests including json
    "org.glassfish.jersey.logging.ServerLoggingFilter": DEBUG
    "org.glassfish.jersey.logging.LoggingFeature": DEBUG

  appenders:
   - type: console
   - type: file
     currentLogFilename: ./default.log
     archive: true
     archivedLogFilenamePattern: ./default-%d.log.gz
     archivedFileCount: 7
     timeZone: UTC
