# H2 DB
database:
    driverClass: org.h2.Driver
    user: sa
    password:
    logValidationErrors: false
    url: jdbc:h2:file:/opt/database/wanthavers-db

    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      #hibernate.hbm2ddl.auto: validate
      hibernate.hbm2ddl.auto: update