# H2 DB
database:
    driverClass: org.h2.Driver
    user: sa
    password:
    logValidationErrors: false
    url: ${DW_DATABASE_URL:-jdbc:h2:./wanthavers-db}

    properties:
      hibernate.dialect: de.fau.cs.mad.wanthavers.server.misc.FixedH2Dialect
      hibernate.hbm2ddl.auto: ${DW_HBM2DDL:-validate}

swagger:
    resourcePackage: de.fau.cs.mad.wanthavers.common.rest.api