# H2 DB
database:
    driverClass: org.h2.Driver
    user: sa
    password:
    logValidationErrors: false
    url: ${DW_DATABASE_URL:-jdbc:h2:./wanthavers-db}

    properties:
      hibernate.dialect: de.fau.cs.mad.wanthavers.server.misc.FixedH2Dialect
      hibernate.hbm2ddl.auto: ${DW_HBM2DDL:-validate}

server:
  applicationConnectors:
    - keyStorePassword: ${KEYSTOREPW}
      keyStorePath: keystore.jks
      type: https
      port: 8443
      validateCerts: false
#      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts