CREATE SEQUENCE PUBLIC.USERFLAGSEQ START WITH 1 INCREMENT BY 50;

CREATE CACHED TABLE PUBLIC.USERFLAG(
    ID BIGINT NOT NULL,
    LASTMODIFIED TIMESTAMP,
    ISSUERID BIGINT NOT NULL,
    USERID BIGINT NOT NULL
);

CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_1E ON PUBLIC.USERFLAG(ID);

ALTER TABLE PUBLIC.USERFLAG ADD CONSTRAINT PUBLIC.CONSTRAINT_1E PRIMARY KEY(ID) INDEX PUBLIC.PRIMARY_KEY_1E;